[package]
name = "rust-docs-pic"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
handlebars = "6.4.0"
serde = {version = "1.0.228", features = ["derive"]}
toml = "1.0.3"
tree-sitter = "0.26.6"
tree-sitter-rust = "0.24.0"
walkdir = "2.5.0"
